global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yaml

scrape_configs:
  - job_name: 'credit-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['credit-api:8000']
