apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: credit-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: credit-api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: credit-api
                port:
                  name: http
