apiVersion: v1
kind: Service
metadata:
  name: credit-api
spec:
  selector:
    app: credit-api
  trafficPolicy:
    weighted:
      - version: stable
        weight: 90
      - version: canary
        weight: 10
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
